# Generated by Django 6.0.5 on 2026-05-24 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itemrequest',
            constraint=models.UniqueConstraint(fields=('item', 'requester'), name='unique_request_per_user_item'),
        ),
    ]
